### ISSUE TITLE
Add CMake build support for tests

### ISSUE THREAD

**Issue by mlxd** [PennyLaneAI/pennylane-lightning#103]
Currently, the package has compilation support using a Makefile, and additional build/install support within `setup.py`. Replacing the tests Makefile (Linux/Mac only) with CMake will allow for a much easier compilation experience.

The following CMake features will be required:
- Use features of CMake language from version 3.14 and previous only.
- Enable C++11 as required C++ standard.
- Link against dependent libraries: Pybind11
- Build generates test binary (see [here](https://github.com/PennyLaneAI/pennylane-lightning/blob/master/pennylane_lightning/src/tests/Makefile)) that runs C++ test suite and mirrors existing Makefile build.

The following features are currently optional:
- Testing and verification of cross-platform compilation (CMake is supported on Win, Mac, Linux).
- Enable compile-time flags for different optimizations (e.g `-march=native`, `-flto`, etc.).
- Tie tests into CMake CTest infrastructure.
- Support for entire package to be compiled using CMake.

**Comment by chaeyeunpark** [comment]
Is pybind11 necessary? It seems like the test code does not use pybind11.

**Comment by mlxd** [comment]
Hi @chaeyeunpark 
The C++-only tests can be built without Pybind11, so feel free to leave this library out if you think it is not needed here.

Though, for the optional feature `Support for entire package to be compiled using CMake.`  Pybind11 will most-definitely be a requirement :slightly_smiling_face:
