### ISSUE TITLE
Github Actions fail due to deprecation of Python 3.6 in PL 0.16.0

### ISSUE THREAD

**Issue by mlxd** [PennyLaneAI/pennylane-lightning#105]
Due to the deprecation of Python 3.6 in the [0.16.0 PennyLane release](https://github.com/PennyLaneAI/PennyLane#installation), Lightning requires updating all Python versions to match. This currently causes tests to fail with the Ubuntu latest wheel build (see PR https://github.com/PennyLaneAI/pennylane-lightning/pull/104#issuecomment-869495170 )

Tasks:
- The Github Actions should be updated to use a newer (3.7+) python version.

**Comment by antalszava** [comment]
Let me make an update to adjust this. :slightly_smiling_face:
