### ISSUE TITLE
Add support for controlled phase gate (ControlledPhaseShift/CPhase)

### ISSUE THREAD

**Issue by mlxd** [PennyLaneAI/pennylane-lightning#112]
Use of the `ControlledPhaseShift` gate is currently supported by PennyLane default_qubit in Python (see [here](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/devices/default_qubit.py) for supported gates and [here](https://github.com/PennyLaneAI/pennylane/blob/a5b9b23952b7cad3528d0b64f1084d0e40b563ab/pennylane/ops/qubit.py#L900) for the Python implementation). This gate should also be natively supported in the C++ layer by lightning.qubit.

This will require the following steps:
 - A new `ControlledPhaseShift` class is created mirroring existing C++ gate structures (see [here](https://github.com/PennyLaneAI/pennylane-lightning/tree/master/pennylane_lightning/src)).
 - The new class is added to the list of supported gates.
 - The new class matches the functionality of the Python implementation.
 - Tests are added for the new gate (see [here](https://github.com/PennyLaneAI/pennylane-lightning/tree/master/pennylane_lightning/src/tests)).

**Comment by maliasadi** [comment]
Important notes to double-check before a pull request:
	1. Named this new gate `CPhaseShiftGate`, to keep the name consistency of derived gates; 
	2. Added a bulk of comments describing this new gate at `Gates.hpp:362`;
	3. Matched all functionalities of this new gate with the implemented ones, however, in comparison with the Python implm., there are `_eigvals` (returning eigenvalues), and decomposition methods that I wasn't sure about implementing them. Let me know if they are required too; and 
	4. Utilized gtest suites of `lightning_gates_unittest.cpp` to test new routines.

**Comment by mlxd** [comment]
> 1. Named this new gate `CPhaseShiftGate`, to keep the name consistency of derived gates;

Yep, that is fine.

> 2. Added a bulk of comments describing this new gate at `Gates.hpp:362`;

Comments are usually a good call

> 3. Matched all functionalities of this new gate with the implemented ones, however, in comparison with the Python implm., there are `_eigvals` (returning eigenvalues), and decomposition methods that I wasn't sure about implementing them. Let me know if they are required too; and

There should be no hard requirement for these, if they are not implemented for other existing C++ methods.

> 4. Utilized gtest suites of `lightning_gates_unittest.cpp` to test new routines.

:+1: 

We will do a review of the PR, and can make suggestions once it is created. Feel free to create it and tag people as needed.
