### ISSUE TITLE
Custom gate fails to run on Lightning backend

### ISSUE THREAD

**Issue by ankit27kh** [PennyLaneAI/pennylane-lightning#139]
-------------------------------------------------------------------------------------------------------------

#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)
Get gradient value.
* *Actual behavior:* (What actually happens)
Errors out
* *Reproduces how often:* (What percentage of the time does it reproduce?)
100%. tried updating to no avail.
* *System information:* (post the output of `import pennylane as qml; qml.about()`)
Name: PennyLane
Version: 0.16.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: \lib\site-packages
Requires: appdirs, scipy, autograd, autoray, semantic-version, numpy, toml, networkx
Required-by: pennylane-qulacs, PennyLane-qiskit, PennyLane-Lightning
Platform info:           Windows-10-10.0.19043-SP0
Python version:          3.9.6
Numpy version:           1.20.3
Scipy version:           1.6.2
Installed devices:
- default.gaussian (PennyLane-0.16.0)
- default.mixed (PennyLane-0.16.0)
- default.qubit (PennyLane-0.16.0)
- default.qubit.autograd (PennyLane-0.16.0)
- default.qubit.jax (PennyLane-0.16.0)
- default.qubit.tf (PennyLane-0.16.0)
- default.tensor (PennyLane-0.16.0)
- default.tensor.tf (PennyLane-0.16.0)
- qulacs.simulator (pennylane-qulacs-0.16.0)
- qiskit.aer (PennyLane-qiskit-0.16.0)
- qiskit.basicaer (PennyLane-qiskit-0.16.0)
- qiskit.ibmq (PennyLane-qiskit-0.16.0)
- lightning.qubit (PennyLane-Lightning-0.17.0)
#### Source code and tracebacks
```
import pennylane as qml
import numpy as np

class MyRX(qml.operation.Operation):
    num_params = 1
    num_wires = 1
    par_domain = "R"
    is_composable_rotation = True
    basis = "X"
    grad_method = "F"

    @classmethod
    def _matrix(cls, *params):
        return qml.RX._matrix(*params)

dev = qml.device('lightning.qubit', wires=3)
dev.operations.add("MyRX")

@qml.qnode(dev, diff_method='best')
def circuit(x):
    MyRX(x, wires=1)
    return qml.expval(qml.PauliZ(1))

par = qml.numpy.array(0.3)
qml.grad(circuit)(par)
```
Results in :
```
Traceback (most recent call last):
  .
  .
    qml.grad(circuit)(par)
  File "\pennylane\_grad.py", line 101, in __call__
    grad_value, ans = self._get_grad_fn(args)(*args, **kwargs)
  File "\autograd\wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "\pennylane\_grad.py", line 118, in _grad_with_forward
    vjp, ans = _make_vjp(fun, x)
  File "\autograd\core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "\autograd\tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "\autograd\wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "\pennylane\qnode.py", line 602, in __call__
    res = self.qtape.execute(device=self.device)
  File "\pennylane\tape\tape.py", line 1277, in execute
    return self._execute(params, device=device)
  File "\autograd\tracer.py", line 44, in f_wrapped
    ans = f_wrapped(*argvals, **kwargs)
  File "\autograd\tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "\pennylane\interfaces\autograd.py", line 165, in _execute
    res = self.execute_device(params, device=device)
  File "\pennylane\tape\tape.py", line 1308, in execute_device
    res = device.execute(self)
  File "\pennylane\_qubit_device.py", line 194, in execute
    self.apply(circuit.operations, rotations=circuit.diagonalizing_gates, **kwargs)
  File "\pennylane_lightning\lightning_qubit.py", line 112, in apply
    self._pre_rotated_state = self.apply_lightning(self._state, operations)
  File "\pennylane_lightning\lightning_qubit.py", line 140, in apply_lightning
    apply(state_vector, op_names, op_wires, op_inverse, op_param)
IndexError: invalid unordered_map<K, T> key
```
Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by trbromley** [comment]
Hey @ankit27kh and thanks for sharing!

Looking through the code you shared, the error may be linked to defining the custom `MyRX` gate. Please could you confirm whether the following successfully provides the gradient:
```python
import pennylane as qml
from pennylane import numpy as np

dev = qml.device('lightning.qubit', wires=1)

@qml.qnode(dev)
def circuit(x):
    qml.RX(x, wires=0)
    return qml.expval(qml.PauliZ(0))

par = np.array(0.3)
qml.grad(circuit)(par)
```

Regarding the use of the custom `MyRX` gate, I'm curious what the use case is? It might be useful to check out the [available operations](https://pennylane.readthedocs.io/en/stable/introduction/operations.html#qubit-operations) in PennyLane. If you have an arbitrary unitary, you may want to consider using [qml.QubitUnitary](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.QubitUnitary.html).

Hope this helps!

**Comment by antalszava** [comment]
Hi @trbromley, this code was created to show a particular example for when we specify `diff_method='best'` and use finite differences to estimate the gradient. `MyRX` was created as an example of an operation that doesn't support analytic gradients. See the [original comment here](https://github.com/PennyLaneAI/pennylane/pull/1568#discussion_r694229356).

**Comment by mlxd** [comment]
Hi @antalszava. Lightning's current design will not support the use of custom gates in this way, as we intended to allow use of the supported gate-set and anything else to require use of the explicit matrix for custom gates.

Is the above example something we should be supporting?

**Comment by antalszava** [comment]
Hi @mlxd, thanks for the explanation for taking a look! :) The example came up during a discussion, rather than as something that the plugin should support. It was surprising to see the error, as the snippet seems to execute well with the latest `master` version (not with the released version though). There might be perhaps some new updates that allow this to work. All in all, I think this would not be something that lightning should definitely support at the moment.

**Comment by mlxd** [comment]
Can this be closed?
