### ISSUE TITLE
T-gate constexpr function definition is incorrect

### ISSUE THREAD

**Issue by mlxd** [PennyLaneAI/pennylane-lightning#178]
#### Issue description
The definition of the T-gate in `Gates.hpp` currently mirrors the S gate. This should be rectified. The gate definitions are not currently used in gate applications, and so does not affect program correctness.

* *Expected behavior:* T-gate definition should be correct.

* *Actual behavior:* (What actually happens)

* *Reproduces how often:* (What percentage of the time does it reproduce?)

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

**Comment by chaeyeunpark** [comment]
Close the issue as it is fixed in #212.
 https://github.com/PennyLaneAI/pennylane-lightning/blob/2cb27272c7882c5cf63a0ef047dc37884c113cac/pennylane_lightning/src/gates/Gates.hpp#L88-L92
