### ISSUE TITLE
[BUG] Compilation on Windows fails

### ISSUE THREAD

**Issue by BastianZim** [PennyLaneAI/pennylane-lightning#192]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)

Compilations succeeds.

* *Actual behavior:* (What actually happens)

Compilation fails on windows with `error C2039: 'all_of': is not a member of 'std'`

* *Reproduces how often:* (What percentage of the time does it reproduce?)

Every time 

* *System information:* (post the output of `import pennylane as qml; qml.about()`)

Azure pipelines

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=428105&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=633

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

This occurs in the context of building the package for conda-forge.

* PR: https://github.com/conda-forge/pennylane-lightning-feedstock/pull/3
* Script: `python -m pip install . -vv`
* Build file: https://github.com/conda-forge/pennylane-lightning-feedstock/blob/f455c7dad8dc571f24fd977eb661fbaf2cf1c209/recipe/meta.yaml

**Comment by mlxd** [comment]
Hi @BastianZim thanks for reporting this.
I suspect this is either a C++17 flag issue for the compiler, or the platform doesn't pull in the header provided for the `std` method. I'll have somebody look at this.

**Comment by BastianZim** [comment]
Thanks @mlxd Let me know if you need more info here from me.

**Comment by mlxd** [comment]
Thanks @BastianZim . We did notice this may be for a Py3.10 build. Due to restrictions in Pennylane's other dependencies we do not currently support Python 3.10.

As for the observed error, we will issue a bugfix release shortly.

**Comment by BastianZim** [comment]
Thanks @mlxd! Pyhton3.10 is not a huge concern, it's just currently passing on the other platforms which is why I had included it. I'll remove Windows for this build and merge it then.

**Comment by mlxd** [comment]
Hi @BastianZim thanks again for reporting this. The problem you found will be fixed in the minor release [v0.20.1](https://github.com/PennyLaneAI/pennylane-lightning/releases/tag/v0.20.1)

**Comment by BastianZim** [comment]
Hi @mlxd can confirm that it is working. Thanks again for the quick fix!
