### ISSUE TITLE
Memory loss in lightning.qubit

### ISSUE THREAD

**Issue by aymeric-degroote** [PennyLaneAI/pennylane-lightning#206]
#### Issue description

Memory loss occurs when training a Variational Quantum Classifier with lightning.qubit. This [Python code](https://github.com/PennyLaneAI/pennylane-lightning/files/7856482/lightning_bug.txt) brings out the difference of memory usage between lightning.qubit and default.qubit.

Here is the plot of memory usage over time of lightning.qubit vs. default.qubit:
![lightning_bug_plot](https://user-images.githubusercontent.com/58313873/149189907-eb02947d-57fd-4011-8515-5b4392619927.png)
And a few screenshots taken over time:
![lightning_bug_1](https://user-images.githubusercontent.com/58313873/149190276-3d734e7d-8921-4aeb-b37d-15e7a8492810.png)
![lightning_bug_2](https://user-images.githubusercontent.com/58313873/149190299-05282074-155a-4fc7-b934-62d26d4a5b2a.png)
![lightning_bug_3](https://user-images.githubusercontent.com/58313873/149190307-2a5601a8-db16-4845-9248-08592042b380.png)

* *Expected behavior:* Similar behavior for lightning and default

* *Actual behavior:* lightning has an increasing memory usage over time

* *Reproduces how often:* Reproductible anytime

* *System information:* 
Name: PennyLane
Version: 0.19.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: Aymeric Degroote
Author-email: aymeric.degroote@prevision.io
License: Apache License 2.0
Location: /home/aymeric/.local/lib/python3.8/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, scipy, semantic-version, toml
Required-by: PennyLane-Lightning, PennyLane-SF, prevision-quantum-nn
Platform info:           Linux-5.11.0-44-generic-x86_64-with-glibc2.29
Python version:          3.8.10
Numpy version:           1.21.2
Scipy version:           1.7.1
Installed devices:
- default.gaussian (PennyLane-0.19.1)
- default.mixed (PennyLane-0.19.1)
- default.qubit (PennyLane-0.19.1)
- default.qubit.autograd (PennyLane-0.19.1)
- default.qubit.jax (PennyLane-0.19.1)
- default.qubit.tf (PennyLane-0.19.1)
- default.qubit.torch (PennyLane-0.19.1)
- default.tensor (PennyLane-0.19.1)
- default.tensor.tf (PennyLane-0.19.1)
- strawberryfields.fock (PennyLane-SF-0.19.0)
- strawberryfields.gaussian (PennyLane-SF-0.19.0)
- strawberryfields.gbs (PennyLane-SF-0.19.0)
- strawberryfields.remote (PennyLane-SF-0.19.0)
- strawberryfields.tf (PennyLane-SF-0.19.0)
- lightning.qubit (PennyLane-Lightning-0.20.2)

**Comment by mlxd** [comment]
Hi @aymeric-degroote thanks for the notification here. I am having troubling replicating this behaviour locally.
Can I ask, if you wouldn't mind creating a fresh environment and running with the following:

```bash
python3 -m venv test_env
source test_env/bin/activate
python3 -m pip install pennylane
python3 ./your_script.py
```

I suspect this may be due to the PennyLane package versions at v0.19, and lightning at v0.20. If the above succeeds, you can upgrade the PennyLane environment with `python3 -m pip install --upgrade pennylane`

**Comment by aymeric-degroote** [comment]
Hi @mlxd, good guess! You were right, I needed to update my version of PennyLane. Note that we have the same issue with pennylane 0.19 et lightning 0.18, so the bug might have come from pennylane 0.19 rather than lightning.
Thanks a lot

**Comment by mlxd** [comment]
No problem at all. Thanks again for reporting this.
