### ISSUE TITLE
Pytest fails on Windows

### ISSUE THREAD

**Issue by chaeyeunpark** [PennyLaneAI/pennylane-lightning#209]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/xanaduai/pennylane-lightning/issues

If posting a PennyLane-Lightning issue, delete everything above the dashed line, and fill
in the template. If the issue is a bug, start the title of the issue with [BUG].

If making a feature request, delete the following template and describe, in detail,
the feature and why it is needed.

For general technical details check out our documentation:
https://pennylane-lightning.readthedocs.io/

-------------------------------------------------------------------------------------------------------------

#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen) `pytest` should work on Windows

* *Actual behavior:* (What actually happens) `pytest` fails due to `np.complex256` which is not available on Windows (see https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.clongdouble)

* *Reproduces how often:* (What percentage of the time does it reproduce?) Always

* *System information:* (post the output of `import pennylane as qml; qml.about()`) Windows

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

As this only a few people use Pennylane on Windows and this is almost nothing to do with a user code, I don't think this is an urgent issue.

**Comment by josh146** [comment]
Nice catch @chaeyeunpark! Although I wonder why the automatic tests that are being run by cibuildwheel after the Windows wheel is created isn't catching this?

> As this only a few people use Pennylane on Windows and this is almost nothing to do with a user code, I don't think this is an urgent issue.

Could a user have the same issue if they repeat the same code that is written in the tests? Or are the tests explicitly setting `complex256` as a test case?

**Comment by chaeyeunpark** [comment]
Hi @josh146! Thanks for the comments/questions. Currently, our GitHub action only runs `pl-device-test` not the whole `pytest`. 

In addition, the errors are raised only because there is no attribute named `complex256` in `numpy` on Windows as  it is just an alias defined in Linux (https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.clongdouble). 256 bit complex numbers are not supported by lightning even in Linux environments. In fact,

**Comment by mlxd** [comment]
I think we can remove the `complex256` from checks/tests. No long-term hardware support exists on any platform, and as reported the tooling only supports this on Linux.
