### ISSUE TITLE
Python test suite in Lightning fails after removing deprecated tape execution methods in PennyLane

### ISSUE THREAD

**Issue by maliasadi** [PennyLaneAI/pennylane-lightning#269]
Removing deprecated tape execution methods in PennyLane (PR [#2339](https://github.com/PennyLaneAI/pennylane/pull/2339)) fails  Lightning Python tests. We should remove the deprecated `tape.execute()` and `tape.execute_device()` methods.

**Comment by josh146** [comment]
@maliasadi let me know how this one goes, and if you need any help/changes are needed to PL.

Hopefully, this should just be a case of updating places in the test where `tape.execute(dev)` are called, to `dev.execute(tape)` or `dev.batch_execute([tape])`.

**Comment by josh146** [comment]
Or the solution you have of `qml.execute([tape])` should also work, and is maybe more future proof :)
