### ISSUE TITLE
PR documentation builds

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane-lightning#42]
Currently, if the environment variable `MOCK_DOCS` is set, the `setup.py` file will skip the building of the wheels. This is required for ReadTheDocs, where C++ extensions cannot be built.

Unfortunately, ReadTheDocs environment variables are not passed to PRs and forks, so we cannot activate the option to build the docs for PRs. An alternative option would be to simply mock out the C++ extensions in the `conf.py` file, like we do for The Walrus.

**Comment by trbromley** [comment]
@josh146, do we still need something in `setup.py` that allows us to install PennyLane-Lightning without having things like Eigen?

**Comment by josh146** [comment]
@trbromley, with the new device, is this issue now closed?

**Comment by trbromley** [comment]
@josh146 we still have [MOCK_DOCS](https://github.com/PennyLaneAI/pennylane-lightning/blob/b0910bc38814944c07390db732e2b0925ce96d52/setup.py#L120) in `setup.py` so I believe it would still be a blocker for PR docs builds.

Could we remove `MOCK_DOCS`? :thinking: I'm not sure, the main difference with the new device is removing the `Eigen` dependency, but we still do load the C++ extensions within the `if`-statement. Probably the best option would be to follow what is done in the Walrus.

**Comment by trbromley** [comment]
I believe you can now share env variables with PR builds: https://github.com/readthedocs/readthedocs.org/issues/7182#issuecomment-839037501. Will have a go!

**Comment by mlxd** [comment]
Docs now build in each PR. Closing.
