### ISSUE TITLE
[BUG] clang-tidy error with aarch64 builds

### ISSUE THREAD

**Issue by dmclark17** [PennyLaneAI/pennylane-lightning#560]
#### Issue description

I am observing a compiler error on ARM systems with clang-tidy enabled. On an ARM Neoverse-N1 system with Ubuntu 22.04.2 and gcc-12.1, I get the following error.

```
cd /pennylane-lightning-gpu/Build/_deps/pennylane_lightning-build/pennylane_lightning/core/src/utils && /usr/local/bin/cmake -E __run_co_compile --tidy="clang-tidy;-extra-arg=-std=c++20;--extra-arg-before=--driver-mode=g++" --source=/pennylane-lightning-gpu/Build/_deps/pennylane_lightning-src/pennylane_lightning/core/src/utils/RuntimeInfo.cpp -- /usr/bin/c++   -O2 -g -DNDEBUG -std=gnu++20 -fPIC -MD -MT _deps/pennylane_lightning-build/pennylane_lightning/core/src/utils/CMakeFiles/lightning_utils.dir/RuntimeInfo.cpp.o -MF CMakeFiles/lightning_utils.dir/RuntimeInfo.cpp.o.d -o CMakeFiles/lightning_utils.dir/RuntimeInfo.cpp.o -c /pennylane-lightning-gpu/Build/_deps/pennylane_lightning-src/pennylane_lightning/core/src/utils/RuntimeInfo.cpp
/pennylane-lightning-gpu/Build/_deps/pennylane_lightning-src/pennylane_lightning/core/src/utils/RuntimeInfo.cpp:130:35: error: use '= default' to define a trivial default constructor [hicpp-use-equals-default,modernize-use-equals-default,-warnings-as-errors]
RuntimeInfo::InternalRuntimeInfo::InternalRuntimeInfo(){};
                                  ^                    ~~
                                                       = default;
```

The error is also reproduced with gcc11.3 and clang 15.0.7.

#### Source code and tracebacks

The error seems to be coming from this line: https://github.com/PennyLaneAI/pennylane-lightning/blob/bf6e121f9b48e177b0f2c1f09a84c119e9081054/pennylane_lightning/core/src/utils/RuntimeInfo.cpp#L130

Switching to using `= default` to define a trivial default compiler resolves the error for me

**Comment by CatalinaAlbornoz** [comment]
Hi @dmclark17, thank you for reporting this bug! We will investigate and come back to you.

**Comment by mlxd** [comment]
Hi @dmclark17 thanks for your patience on this. We have a PR to rectify the above clang-tidy warning turned error with https://github.com/PennyLaneAI/pennylane-lightning/pull/567

It will also resolve a few additional clang-tidy related warnings we found under development.
