### ISSUE TITLE
Pytest tests hang on Windows

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane-lightning#60]
Two test cases were found to cause hanging behaviour when [using `pytest` on a Windows machine](https://github.com/PennyLaneAI/pennylane-lightning/runs/1813396596?check_suite_focus=true):
1. `test_four_qubit_random_circuit` from the PennyLane device test suite;
2. `test_apply_operation_single_wire_with_parameters` from the PennyLane-Lightning test suite when passing the `Rot` gate and the second input parameter.

Running these tests cause the suites to run without termination. When run as a stand-alone case, the code for 1. could be executed with/without using `pytest`.

#59 includes a small fix to split up running 1. and the rest of the device tests when building the wheel.

**Comment by josh146** [comment]
Are the two tests with the issues related? Maybe they are both applying a `Rot` gate with problematic parameters/wires/qubit number?
