### ISSUE TITLE
[BUG] We're linking to the old readthedocs docs in several places

### ISSUE THREAD

**Issue by CatalinaAlbornoz** [PennyLaneAI/pennylane-lightning#820]
Some lightning errors point users to look at a link that doesn't exist anymore (the old docs).
We should change the link in the errors to the appropriate links in the new docs.

[Here](https://github.com/search?q=repo%3APennyLaneAI%2Fpennylane-lightning+readthedocs&type=code) are several instances referencing readthedocs.

It includes two links to the old [installation link](https://pennylane-lightning.readthedocs.io/en/latest/installation.html) in two errors.
These should be changed to this link instead: https://docs.pennylane.ai/projects/lightning/en/stable/dev/installation.html

It also includes the old link in the issue template:

> For general technical details check out our documentation:
> https://pennylane-lightning.readthedocs.io/

This should be changed to this link instead: https://docs.pennylane.ai/projects/lightning/en/stable

**Comment by maliasadi** [comment]
Ahh, thanks @CatalinaAlbornoz for catching these old links!
